<?php
/**@var Hunters\SearchShopMap\ViewModel\Search $viewModel*/
$viewModel = $this->getData('viewModel');

$myCollection = $viewModel->getMyCustomCollection()->getData();
$resultCoordinate = $viewModel->coordinateArray($myCollection);

?>

<form action="#" accept-charset="utf-8" method="POST" onSubmit="return false;">
        <input  class="zipsearch" type="search" name="zipjson">
        <input  class="sendZip" type="submit" value="Send">
</form>
</br>
<div>
    <span class="cord"></span>
    </br>
    <span class="state"></span>
</div>
</br>
<div id="google-map" ></div>
</br>
<table id="companytableinfo" border="1" style="display: none">
    <tr>
        <th>Name</th>
        <th id="namecompany"></th>
    </tr>
    <tr>
        <th>Street</th>
        <th id="streetcompany"></th>
    </tr>
    <tr>
        <th>Phone</th>
        <th id="phonecompany"></th>
    </tr>
    <tr>
        <th>postcode</th>
        <th id="postcodecompany"></th>
    </tr>
</table>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBSiWyPtBS2Esy_ObhOSQJT81AfU3jyXcQ&callback=initMap">
</script>

<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            let array_cordinate = <?php echo json_encode($resultCoordinate); ?>;
            var s = '<script src="https://polyfill.io/v3/polyfill.min.js?features=default"/>';
            var ss = '<script src="https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js"/>';
            $('head').append(s);
            $('head').append(ss);
            $(".sendZip").click(function (e) {
                    var zip = $(".zipsearch").val();
                    var url = "<?php echo $this->getUrl('searchjson/page/ajax', ['_secure' => false]) ?>";
                    $.ajax({
                        url: url,
                        type: "POST",
                        data: {
                            zip:zip
                        },
                        showLoader: true,
                        cache: false,
                        complete: function(response) {
                            var res = $.parseJSON(response.responseText);
                            if (($.parseJSON(res.loc)) !== null) {
                                var coordinate = ($.parseJSON(res.loc)).coordinate;
                                var state = ($.parseJSON(res.loc)).state;
                                $(".cord").text("Your coordinates: lat = " + coordinate.lat + "; lng = " + coordinate.lng + ";");
                                $(".state").text("Your coordinates:  " + state + ";");
                                initMap(coordinate);
                            }
                            else {
                                alert("No search you zip: "+zip+" code!");
                            }
                        },
                        error: function (xhr, status, errorThrown) {
                            console.log('Error happens. Try again.');
                        }
                    });
            });

            const  locations = array_cordinate;

            function initMap(myCoordinate) {
                const  myLatLng = myCoordinate;
                const map = new google.maps.Map(document.getElementById("google-map"), {
                zoom: 10,
                center: myLatLng,
            });
                new google.maps.Marker({
                     position: myLatLng,
                     map,
                     title: "My location!",
                     icon: {
                         url: "https://upload.wikimedia.org/wikipedia/commons/3/38/Simpleicons_Places_flag-map-marker-1.svg",
                         scaledSize: new google.maps.Size(35, 35)
                        }
                    });
                var infoWindow = new google.maps.InfoWindow();
                var latlngbounds = new google.maps.LatLngBounds();
                var all_markers = [];
                for (var i = 0; i < locations.length; i++) {
                    var data = locations[i];
                    var cord = $.parseJSON(data['coordinate']);
                    var myLatlng = new google.maps.LatLng(cord.lat, cord.lng);
                    var marker = new google.maps.Marker({
                        position: myLatlng,
                        map: map,
                        title: data.company_name
                    });
                    all_markers.push(marker);
                    (function (marker, data) {
                        google.maps.event.addListener(marker, "click", function (e) {
                            infoWindow.setContent("<div style = 'width:200px;min-height:40px'>" + data.company_name+ "</br>" +" tel. "+data.telephone+  "</div>");
                            infoWindow.open(map, marker);
                            $('#namecompany').text("").append(data.company_name);
                            $('#streetcompany').text("").append(data.street);
                            $('#phonecompany').text("").append(data.telephone);
                            $('#postcodecompany').text("").append(data.postcode);
                            $('#companytableinfo').css('display', 'block');
                        });
                    })(marker, data);
                }
                new MarkerClusterer(map, all_markers, {
                        imagePath: "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m",
                });
            }
        });
    });
</script>

